# Generated by Django 5.1.7 on 2025-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="upload/product/"),
        ),
    ]
